### ISSUE TITLE
break points do not work

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [cedricdelpoux/react-responsive-masonry#11]
the break points do not work even on demo https://xuopled.github.io/react-responsive-masonry/
using chrome Version 63.0.3239.84 (Official Build) (64-bit) and macOS Sierra

**Comment by cedricdelpoux** [comment]
It's working now https://cedricdelpoux.github.io/react-responsive-masonry/. Scroll to see the responsive masonry
