### ISSUE TITLE
Change each column's inline styles

### ISSUE THREAD

**Issue by JacobCll** [cedricdelpoux/react-responsive-masonry#122]
The library has been very useful to me however I couldn't further tweak how the columns would behave because there is no way, as far as I know, for me to change each column's assigned inline styles.

a column's inline styles:
`<div style="display: flex; flex-direction: column; place-content: stretch flex-start; flex: 1 1 0%; width: 0px; gap: 0px;"></div>` 

Is there a workaround to changing these inline styles? It would be useful if there were a way to change how each column behaved.

**Comment by cedricdelpoux** [comment]
There is a new `itemStyle` prop available in v`2.3.0`. You can check the README
