### ISSUE TITLE
Masonry2` uses `getDerivedStateFromProps` but its initial state is undefined.

### ISSUE THREAD

**Issue by shajal-kumer** [cedricdelpoux/react-responsive-masonry#133]
Warning: `Masonry2` uses `getDerivedStateFromProps` but its initial state is undefined. This is not recommended. Instead, define the initial state by assigning an object to `this.state` in the constructor of `Masonry2`. This ensures that `getDerivedStateFromProps` arguments have a consistent shape. Error Component Stack

**Comment by ADTC** [comment]
Duplicate of #131

**Comment by cedricdelpoux** [comment]
Hello, I reverted the commits that caused this issue and published an `v2.5.0`.
Tell me if the regression is gone for you.

Thanks
