### ISSUE TITLE
Publish react 17 peer dependency fix to npm

### ISSUE THREAD

**Issue by in43sh** [cedricdelpoux/react-responsive-masonry#31]
I'm trying to install this package for my React project. I have React version 17.0.1. Here is the error that my console gives to me when I try to install it:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front-end-nextjs@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-responsive-masonry@2.1.1
npm ERR! node_modules/react-responsive-masonry
npm ERR!   react-responsive-masonry@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/serg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serg/.npm/_logs/2021-02-25T06_41_26_421Z-debug.log

**Comment by cosmosdesigner** [comment]
+1 @cedricdelpoux

**Comment by cedricdelpoux** [comment]
published in `2.1.2`
