### ISSUE TITLE
Making single child centered?

### ISSUE THREAD

**Issue by TheSayantan96** [cedricdelpoux/react-responsive-masonry#45]
Is there a way we can make a single child horizontally center aligned?

**Comment by keegandonley** [comment]
FWIW I had a similar use case and was able to accomplish it by pre-calculating how many children I would have:

```jsx
<ResponsiveMasonry columnsCountBreakPoints={children.length === 1 ? { 0: 1 } : { 1023: 1, 1024: 2 }}>
    <Masonry columnsCount={children.length === 1 ? 1 : undefined}>
        {...children}
    </Masonry>
</ResponsiveMasonry>
     
```

Not sure if this is the best/only approach but it works well for me

**Comment by cedricdelpoux** [comment]
This is the best approach for now. Thanks @keegandonley
