### ISSUE TITLE
Custom HTML tag for masonry and items

### ISSUE THREAD

**Issue by jahirfiquitiva** [cedricdelpoux/react-responsive-masonry#53]
Hi

I would like to be able to set the HTML tag for the masonry to be `ul` or `ol` and the items to use `li`

Is this possible already? If so, how to? Otherwise, would you mind adding this feature?

Thanks

**Comment by aalpgiray** [comment]
Hey! Did you implement something to solve this? Or is this project still maintained? if I create a PR will we merge it?

**Comment by cedricdelpoux** [comment]
PR are welcome :) I will merge it

**Comment by cedricdelpoux** [comment]
Available in v`2.3.0`
