### ISSUE TITLE
Compiled divs include `[object Object]` in attributes

### ISSUE THREAD

**Issue by jahirfiquitiva** [cedricdelpoux/react-responsive-masonry#56]
Hello

when my project is compiled, the `div`s that belong to the masonry include `[object Object]` within some attributes:

```html
<div __self="[object Object]" __source="[object Object]">
    ...
</div>
```

<img width="592" alt="Shot 2021-11-11 at 15-37-38@2x" src="https://user-images.githubusercontent.com/10360816/141365626-0bd4f869-d4f9-4c84-816b-753763254339.png">

**Comment by cedricdelpoux** [comment]
very strange! I don't know where it comes from. If you find solution please make a PR 👍🏻

**Comment by cedricdelpoux** [comment]
In my opinion it's not related to this plugin. "__self" and "__source" are not added by `react-responsive-masonry`
