### ISSUE TITLE
is there a way we can refresh the list?

### ISSUE THREAD

**Issue by mike1011** [cedricdelpoux/react-responsive-masonry#65]
For example - 
```

                    <ResponsiveMasonry
                      columnsCountBreakPoints={{
                        350: 1,
                        750: 3,
                        900: 4
                      }}
                    >
                      <Masonry gutter={'15px'}>
                        {items.map((item) => {
                            <somecustomcomponent />
                        }))
                      </Masonry>
                   </ResponsiveMasonry>
```   
If i want to delete/remove the custom component and also refresh the list, so that it can rearrange the list or trigger it to rearrange again. How can I do it?

**Comment by mike1011** [comment]
Well, I simply used `display:none` dynamically and this triggered the grid to _auto adjust_ again.
Initially, I was using `visibility:hidden`, but seems `display:none` did the trick.

**Comment by ADTC** [comment]
I know it's a bit late to ask this now, but I'm curious why you're not just updating the `items` array by removing the "deleted" items from this array when you no longer want to show them?

The Masonry component will automatically re-render when the array changes.

That's the correct React way, isn't it? @mike1011  🙂
